# Generated by Django 2.2 on 2019-07-26 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cat', models.CharField(max_length=100)),
                ('dt_criacao_cat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao_fab', models.DateTimeField(auto_now_add=True)),
                ('nome_fab', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao_lj', models.DateTimeField(auto_now_add=True)),
                ('nome_lj', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao_sai', models.DateTimeField(auto_now_add=True)),
                ('dt_saida', models.DateTimeField()),
                ('descricao', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=100)),
                ('n_serie', models.IntegerField()),
                ('qtd_saida', models.IntegerField()),
                ('observacao', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Categoria')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Fabricante')),
                ('lj_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Loja')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao_ent', models.DateTimeField(auto_now_add=True)),
                ('dt_entrada', models.DateTimeField()),
                ('descricao', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=100)),
                ('n_serie', models.IntegerField(blank=True, null=True)),
                ('qtd_entrada', models.IntegerField()),
                ('observacao', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Categoria')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Fabricante')),
                ('lj_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Loja')),
            ],
        ),
    ]
