# Generated by Django 2.2 on 2019-08-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='controleti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao_ti', models.DateTimeField(auto_now_add=True)),
                ('Ip_Address', models.GenericIPAddressField(protocol='Ipv4')),
                ('Mac', models.CharField(max_length=17)),
                ('Hostname', models.CharField(max_length=80)),
                ('Setor', models.CharField(max_length=80)),
                ('Responsavel', models.CharField(max_length=120)),
                ('Contato', models.CharField(max_length=120)),
                ('Observacao', models.TextField(max_length=300)),
                ('Servico', models.CharField(max_length=120)),
            ],
        ),
    ]
