# Generated by Django 2.2 on 2019-08-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190815_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleti',
            name='Ip_Address',
            field=models.GenericIPAddressField(protocol='Ipv4'),
        ),
    ]
