# Generated by Django 2.2 on 2019-08-26 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190815_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao_setor', models.DateTimeField(auto_now_add=True)),
                ('nome_setor', models.CharField(default='', max_length=20, verbose_name='Descrição do Setor')),
            ],
        ),
        migrations.RemoveField(
            model_name='controleti',
            name='Setor',
        ),
        migrations.AddField(
            model_name='controleti',
            name='Loja',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.Loja'),
        ),
        migrations.AddField(
            model_name='controleti',
            name='setor',
            field=models.CharField(default='', max_length=30, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome_cat',
            field=models.CharField(max_length=100, verbose_name='Nome da Categoria'),
        ),
        migrations.AlterField(
            model_name='controleti',
            name='Hostname',
            field=models.CharField(max_length=80, verbose_name='Nome da Máquina'),
        ),
        migrations.AlterField(
            model_name='controleti',
            name='Ip_Address',
            field=models.GenericIPAddressField(protocol='Ipv4', verbose_name='Endereço IP'),
        ),
        migrations.AlterField(
            model_name='controleti',
            name='Observacao',
            field=models.TextField(max_length=300, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='controleti',
            name='Responsavel',
            field=models.CharField(max_length=120, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='controleti',
            name='Servico',
            field=models.CharField(max_length=120, verbose_name='Serviços'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='dt_entrada',
            field=models.DateTimeField(verbose_name='Data da Entrada'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Fabricante', verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='lj_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Loja', verbose_name=' Loja Origem'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='modelo',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='n_serie',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº de Série'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='observacao',
            field=models.TextField(verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='qtd_entrada',
            field=models.IntegerField(verbose_name='Qtd. Entrada'),
        ),
        migrations.AlterField(
            model_name='fabricante',
            name='nome_fab',
            field=models.CharField(max_length=100, verbose_name='Nome do Fabricante'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='nome_lj',
            field=models.CharField(default='', max_length=20, verbose_name='Descrição da Loja'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='dt_saida',
            field=models.DateTimeField(verbose_name='Data de Saída'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Fabricante', verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='lj_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Loja', verbose_name='Loja Destino'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='modelo',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='n_serie',
            field=models.IntegerField(verbose_name='Nº de Série'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='observacao',
            field=models.TextField(verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='qtd_saida',
            field=models.IntegerField(verbose_name='Qtd. Saída'),
        ),
    ]
